const UCHICAGO_FACTS: string[] = [
  "Founded in 1890, UChicago received its first major gift of $600,000 from John D. Rockefeller.",
  "On December 2, 1942, Enrico Fermi's team achieved the first self-sustaining nuclear chain reaction under Stagg Field.",
  "Barack Obama taught constitutional law at the Law School for 12 years before becoming president.",
  "UChicago dropped intercollegiate football in 1939 — a decision made by President Robert Maynard Hutchins.",
  "The university has been associated with over 100 Nobel laureates among its faculty, students, and researchers.",
  "Milton Friedman spent most of his career at UChicago, developing monetarism and influencing Reagan-era economic policy.",
  "The campus Gothic architecture was deliberately modeled on Oxford and Cambridge.",
  "UChicago Press published the first edition of the Chicago Manual of Style in 1906.",
  "Carl Sagan received his PhD in astronomy and astrophysics from UChicago in 1960.",
  "The school's motto — 'Crescat scientia; vita excolatur' — means 'Let knowledge grow from more to more; and so be human life enriched.'",
  "Saul Bellow taught at UChicago for decades and won the Nobel Prize in Literature in 1976.",
  "James D. Watson enrolled at UChicago at age 15 through an early admission program before co-discovering DNA's structure.",
  "The Oriental Institute, founded in 1919, holds one of the world's great collections of ancient Near Eastern artifacts.",
  "UChicago co-manages Argonne National Laboratory, one of the US Department of Energy's oldest national labs.",
  "The university began admitting women in 1892, among the earliest major research universities to do so.",
  "The 'Chicago School' of economics has shaped monetary and regulatory policy in dozens of countries.",
  "The Midway Plaisance, which bisects the campus, was the entertainment strip of the 1893 World's Columbian Exposition.",
  "Gary Becker won the Nobel Prize in 1992 for applying economic analysis to social behavior like crime and discrimination.",
  "Ronald Coase developed the Coase theorem — a foundational concept in law and economics — while at UChicago.",
  "The Regenstein Library, opened in 1970, is one of the largest academic research libraries in the United States.",
  "UChicago's annual Scavenger Hunt, held since 1987, is one of the world's largest collegiate scavenger hunts.",
  "Robert Maynard Hutchins became president of UChicago in 1929 at age 30, making him the youngest president of a major US university.",
  "David Booth donated $300 million to the business school in 2008 — the largest gift in business school history at that time.",
  "Thorstein Veblen, who coined the term 'conspicuous consumption,' taught at UChicago in the late 1800s.",
  "John Dewey founded the University of Chicago Laboratory Schools in 1896 as an experimental school for his educational theories.",
  "Robert Millikan performed experiments at UChicago that contributed to measuring the charge of an electron.",
  "Albert Michelson, who led UChicago's physics department, was the first American to win a Nobel Prize in science (1907).",
  "Friedrich Hayek, author of 'The Road to Serfdom,' taught at UChicago from 1950 to 1962.",
  "George Herbert Mead, one of the founders of social psychology, taught at UChicago for nearly 40 years.",
  "James Heckman won the Nobel in Economics in 2000 for work showing the massive long-term returns of early childhood investment.",
  "Frank Lloyd Wright designed the Robie House near campus in 1910, a landmark of his Prairie Style.",
  "Subrahmanyan Chandrasekhar taught at UChicago for decades and won the Nobel Prize in Physics in 1983.",
  "The Fermi National Accelerator Laboratory (Fermilab) is named in honor of UChicago's Enrico Fermi.",
  "Eugene Fama developed the Efficient Market Hypothesis at UChicago Booth — one of the most influential ideas in modern finance.",
  "Richard Thaler, who pioneered behavioral economics and won the Nobel in 2017, taught at UChicago Booth.",
  "Paul Samuelson studied at UChicago before transferring to Harvard, where he would later win the first Nobel in Economics.",
  "Susan Sontag enrolled at UChicago at age 15 through the university's early college program.",
  "George Stigler won the Nobel Prize in Economics in 1982 for his research on industrial organization and regulation.",
  "The Becker Friedman Institute for Economics is named after two of the university's most celebrated economists.",
  "Hannah Arendt was a visiting professor at UChicago's Committee on Social Thought in the 1950s and 1960s.",
  "The Committee on Social Thought has no fixed curriculum — PhD students design their own program of study.",
  "UChicago's 'Core' curriculum requires all undergraduates to engage deeply with foundational texts across multiple disciplines.",
  "Yerkes Observatory in Wisconsin, which UChicago operated for over a century, once housed the world's largest refracting telescope.",
  "Theodore Schultz won the Nobel in Economics in 1979 for his work on agricultural economics and human capital in developing countries.",
  "Robert Lucas won the Nobel in Economics in 1995 for the rational expectations theory developed largely at UChicago.",
  "The Pritzker School of Medicine is consistently ranked among the top ten medical schools in the United States.",
  "UChicago researchers contributed to the development of the first influenza vaccine in the 1930s and 1940s.",
  "The university's uncommon application essays — notoriously creative — are written by current students each year.",
  "UChicago's endowment has grown to exceed $10 billion, funding research across every discipline.",
  "The university sits on 217 acres in the Hyde Park neighborhood on Chicago's South Side.",
  "The Phoenix was chosen as UChicago's mascot after football was dropped — symbolizing rebirth from the ashes.",
  "UChicago's maroon and white colors were officially adopted in 1894, just four years after the university's founding.",
  "The Graduate School of Business, founded in 1898, is one of the oldest business schools in the United States.",
  "Economist George Shultz — later Secretary of State — served as dean of UChicago's business school.",
  "The Law School is widely credited with inventing the field of 'law and economics' as an academic discipline.",
  "Robert Fogel won the Nobel in Economics in 1993 for applying quantitative methods to economic history, including slavery.",
  "The university library system holds over 13 million volumes across its network of specialized libraries.",
  "UChicago hosted the first university-based school of social work in the United States.",
  "The 'Chicago Boys' — economists trained at UChicago — advised governments across Latin America on market reforms.",
  "Astronomer Edwin Hubble, who proved the universe is expanding, completed his PhD at UChicago in 1917.",
  "The Harper Memorial Library was designed in 1912 and named after UChicago's first president, William Rainey Harper.",
  "Myron Scholes, co-developer of the Black-Scholes options pricing model, was a professor at UChicago Booth.",
  "UChicago's Smart Museum of Art holds a permanent collection of over 15,000 works and admission is always free.",
  "The university's annual 'Doc Films' series, running since 1932, is one of the oldest student-run film societies in the US.",
];

export function getRandomFact(): string {
  return UCHICAGO_FACTS[Math.floor(Math.random() * UCHICAGO_FACTS.length)];
}

export default UCHICAGO_FACTS;
